---
title: "hierarchy"
author: "Yanyu Zheng yz2690"
date: "April 9, 2016"
output: html_document
---

## Set up
```{r}
setwd("~/Data Science/project4-team6/data")
library(igraph)
library(bipartite)
library(intergraph)
```

## Read in the graph as adjacency matrix
```{r}
data = read.csv("datawithnameandgenre.csv")
attach(data)
matData = cbind(product_productid,review_userid,review_score,V1.1)
save(matData,file = "matData.RData")
g <- make_empty_graph() +
                 vertices(letters[1:10]) +
                 vertices("foo", "bar", "bar2", "foobar2")
          g <- g + edge("a", "b",weight = 3)

as.matrix.igraph(g,matrix.type = "adjacency")         
sampledata <- rbind(
    c(1,2,4),
    c(1,3,2),
    c(2,1,4),
    c(2,3,4),
    c(2,4,1),
    c(2,5,2),
    c(3,1,2),
    c(3,2,4),
    c(4,2,1),
    c(5,2,2),
    c(5,6,1),
    c(6,5,1))
playdata = cbind(data$product_productid,data$review_userid,data$review_score)[1:500,]

data(Safariland)
plotweb(Safariland)
clustering_tm(Safariland)
compart(Safariland)

## Build adjacency matrix
adjMat = matrix(nrow=length(levels))
```

## Build the hierarchy tree
```{r}

```

